name: Build and Deploy Docs
on:
  push:
    branches:
      - master
      - v*
    tags-ignore:
      - v*
    paths:
      - .dumi/**
      - docs/**
      - src/**
      - .fatherrc.ts
      - .dumirc.js
      - .github/**
      - package.json

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: yarn install
      - name: Build package
        run: yarn build
      - name: Build latest docs
        if: ${{github.ref == 'refs/heads/master'}}
        run: yarn docs
      - name: Deploy latest docs
        if: ${{github.ref == 'refs/heads/master'}}
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.ACCESS_TOKEN_WORKFLOW }}
          branch: gh-pages
          folder: site
          target-folder: latest
      - name: Build version docs
        if: ${{github.ref != 'refs/heads/master'}}
        run: yarn docs-version
      - name: Deploy version docs
        if: ${{github.ref != 'refs/heads/master'}}
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          token: ${{ secrets.ACCESS_TOKEN_WORKFLOW }}
          branch: gh-pages
          folder: site
          target-folder: ${{github.ref}}
